import React from 'react';
import {AbsoluteFill, Audio, Easing, Freeze, Img, OffthreadVideo, Sequence, interpolate, staticFile, useCurrentFrame} from 'remotion';
import {IconArrowLeft, IconArrowUpRight, IconArrowUp, IconAntennaBars5, IconBattery4, IconBrandGmail, IconBrandOpenai, IconBrandWhatsapp, IconCalendar, IconCheck, IconChecks, IconChevronDown, IconFileSpreadsheet, IconPlus, IconWifi, IconX, IconMicrophone, IconPlayerStopFilled, IconWaveSine} from '@tabler/icons-react';
import {SellerMoment, MarketMoment} from '../launch/ProductScenes';
import timeline from './timeline.json';
import './film.css';

const asset=staticFile;
const ease=(f:number,a:number,b:number,x=0,y=1)=>interpolate(f,[a,b],[x,y],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(.22,.72,.2,1)});
const at=(left:number,top:number):React.CSSProperties=>({position:'absolute',left,top});
type Row={id:string;fromFrame:number;frames:number;words:{word:string;start:number;end:number}[]};
function Title({eyebrow,children,sub}:{eyebrow:string;children:React.ReactNode;sub?:string}){return <div className="rf-title"><div className="rf-eyebrow">{eyebrow}</div><h1>{children}</h1>{sub&&<p>{sub}</p>}</div>}
function Base({children,dark=false}:{children:React.ReactNode;dark?:boolean}){return <AbsoluteFill className={`rf-scene${dark?' rf-dark':''}`}>{children}</AbsoluteFill>}
function Phone({children,dark=false,left=1160}:{children:React.ReactNode;dark?:boolean;left?:number}){return <div className="rf-phone" style={{left}}><div className={`rf-phone-screen${dark?' rf-phone-dark':''}`}><div className="rf-status"><span>9:41</span><span><IconAntennaBars5 size={20}/><IconWifi size={20}/><IconBattery4 size={25}/></span></div>{children}<div className="rf-home"/></div></div>}
function Orb({frame,listening=false}:{frame:number;listening?:boolean}){return <svg width="180" height="180" viewBox="0 0 180 180" aria-label="Repeat orb">{Array.from({length:169},(_,i)=>{const x=i%13-6,y=Math.floor(i/13)-6,d=Math.hypot(x/6,y/6),pulse=listening?.15*Math.sin(frame/5+d*5):.05*Math.sin(frame/23+d*3);return d<1.06?<circle key={i} cx={90+x*11} cy={90+y*11} r={Math.max(.8,6.3*Math.exp(-d*d*1.45)*(1+pulse))} fill="currentColor"/>:null})}</svg>}
function Opening({row}:{row:Row}){const f=useCurrentFrame();const q=f/row.frames;return <Base><div className="rf-opening-copy"><div className="rf-eyebrow">A reason to reconnect</div><h1>A recent sale.<br/><span style={{color:'#728564'}}>A relevant update.</span></h1><p style={{opacity:ease(q,.5,.62)}}>A better reason to follow up.</p></div><div className="rf-property" style={{transform:`translateY(${ease(f,0,28,24,0)}px)`}}><Img src={asset('property.png')} style={{width:'100%',height:'100%',objectFit:'cover',transform:`scale(${ease(f,0,row.frames,1,1.045)})`}}/><div className="rf-sale-label"><span>RECENT SALE  /  ST. REGIS</span><strong>AED 6.3M</strong><p>2 bedrooms  /  1,323 sqft</p></div></div><div className="rf-floating-message" style={{opacity:ease(q,.35,.46),transform:`translateY(${ease(q,.35,.5,25,0)}px)`}}><IconBrandWhatsapp size={31}/><div><b>Hi Alex,</b><p>A 2-bed apartment just sold in your building.</p></div><IconChecks size={24}/></div></Base>}
function Brand({close=false}:{close?:boolean}){const f=useCurrentFrame();return <Base dark><div className="rf-brand"><Img src={asset('logo.png')} style={{width:820,opacity:ease(f,0,15),transform:`translateY(${ease(f,0,22,14,0)}px)`}}/>{close&&<><h2>Stay close to your sellers.</h2><div className="rf-cta">Get started at <b>repeatai.org</b><IconArrowUpRight size={34}/></div></>}</div></Base>}
function Import({row}:{row:Row}){const f=useCurrentFrame(),q=f/row.frames,done=q>.5;return <Base><Title eyebrow="Your starting point">Your spreadsheet.<br/>Your sellers, organised.</Title><div className="rf-import-card"><div className="rf-windowbar"><IconFileSpreadsheet size={27}/><b>Spreadsheets</b><span>Repeat AI</span></div><div style={{padding:'44px 48px'}}>{!done?<><h3>Import your sellers</h3><div className="rf-input"><IconFileSpreadsheet size={28}/><span>Downtown sellers.xlsx</span><div className="rf-import-button"><IconPlus size={27}/></div></div><p className="rf-muted">Google Sheets or Excel</p><div className="rf-progress"><div style={{width:`${ease(q,.14,.48,0,100)}%`}}/></div></>:<><div className="rf-import-done"><IconCheck size={26}/> Spreadsheet imported</div>{[['Downtown sellers','8 sellers']].map(([name,count],i)=><div className="rf-building-row" key={name} style={{opacity:ease(q,.5+i*.05,.62+i*.05)}}><IconFileSpreadsheet size={28}/><b>{name}</b><span>{count}</span></div>)}<p className="rf-muted">St. Regis Residences  /  Burj Khalifa</p></>}</div></div></Base>}
function Seller({row}:{row:Row}){const f=useCurrentFrame(),cf=Math.round(ease(f,12,row.frames-20,30,145));return <Base><div className="rf-wide-heading"><span className="rf-eyebrow">Relevant market context</span><h1>The sale. The seller. Together.</h1></div><div className="rf-product-window rf-seller-window"><div className="rf-product-canvas"><Freeze frame={cf}><SellerMoment/></Freeze></div><div className="rf-sale-focus" style={{opacity:ease(f,20,38)}}><span>RECENT SALE</span><strong>AED 6.3M</strong><span>St. Regis Residences  /  2 bedrooms</span></div></div></Base>}
function BrokerCard(){return <div className="rf-broker-card"><Img src={asset('workflow/whatsapp/landing-template-art.png')}/></div>}
function WhatsApp({row}:{row:Row}){const f=useCurrentFrame(),q=f/row.frames;return <Base><Title eyebrow="Make it personal" sub="Your words. Your broker card.">Useful news.<br/><span>A personal touch.</span></Title><Phone><div className="rf-whatsapp-header"><IconArrowLeft size={25}/><div className="rf-avatar">A</div><b>Alex Morgan</b><IconBrandWhatsapp size={28}/></div><div className="rf-today">Today</div><div className="rf-whatsapp-message" style={{opacity:ease(q,.03,.12),transform:`translateY(${ease(q,.03,.16,24,0)}px)`}}><BrokerCard/><div className="rf-wa-copy"><p>Hi Alex,</p><p>Latest sale in St. Regis:</p><p><b>2 bed  /  AED 6.3M</b><br/>1,323 sqft</p><p>Would you like an updated valuation?</p></div><div className="rf-wa-time">9:41 <IconChecks size={21}/></div></div><div className="rf-wa-composer">Message <IconMicrophone size={26}/></div></Phone></Base>}
function Schedule({row}:{row:Row}){const f=useCurrentFrame(),q=f/row.frames;return <Base><div className="rf-wide-heading"><span className="rf-eyebrow">Set your rhythm</span><h1>Your buildings. Your days.</h1></div><div className="rf-schedule"><div className="rf-schedule-head"><span><IconCalendar size={29}/> Weekly schedule</span><div className="rf-save">{q>.73?<><IconCheck size={22}/>Saved</>:'Save'}</div></div><div className="rf-source">Spreadsheet <b>St. Regis Residences</b><IconChevronDown size={24}/></div><div className="rf-days">{['Monday','Wednesday','Friday'].map((day,i)=><div className="rf-day" key={day}><h3>{day}</h3><div className="rf-day-building" style={{opacity:ease(q,.17+i*.14,.25+i*.14),transform:`translateY(${ease(q,.17+i*.14,.28+i*.14,14,0)}px)`}}><span>St. Regis<br/>Residences</span><IconCheck size={23}/></div><div className="rf-add"><IconPlus size={22}/>Add buildings</div></div>)}</div><p className="rf-schedule-note"><IconBrandWhatsapp size={21}/> Connected <span>Automatic follow-ups enabled</span></p></div></Base>}
function Market({row}:{row:Row}){const f=useCurrentFrame();return <Base><div className="rf-wide-heading"><span className="rf-eyebrow">Keep the market in view</span><h1>Spot the price change.</h1></div><div className="rf-product-window rf-market-window"><div className="rf-market-canvas"><Freeze frame={Math.round(ease(f,0,row.frames-35,20,179))}><MarketMoment/></Freeze></div></div></Base>}
function Assistant({row}:{row:Row}){const f=useCurrentFrame();
 const wordAt=(word:string,fallback:number)=>{const found=row.words.find(w=>w.word.toLowerCase().replace(/[^a-z]/g,'')===word);return found?Math.round(found.start*30):row.frames*fallback};
 const tap=wordAt('find',.2),ask=wordAt('draft',.4),review=wordAt('review',.7);
 const requestAt=Math.max(tap+34,ask),resultAt=Math.max(requestAt+56,review-48),saveAt=row.frames-30;
 const listening=f>=tap&&f<resultAt, result=f>=resultAt,saved=f>=saveAt;
 const request='Create a follow-up template.';const typed=request.slice(0,Math.floor(ease(f,requestAt,requestAt+48,0,request.length)));
 return <Base><div className="rf-assistant-copy"><div className="rf-eyebrow">Ask Repeat <span className="rf-early">Early access</span></div><h1>Your assistant.<br/><span>In your pocket.</span></h1><div className="rf-assistant-steps"><div className={f<tap?'active':''}>Talk or type.</div><div className={listening?'active':''}>Tell it what you need.</div><div className={result?'active':''}>Review before saving.</div></div></div><Phone dark><div className="rf-assistant-head"><b>Repeat AI</b><IconPlus size={28}/><IconX size={26}/></div>{!result?<div className="rf-listening"><Orb frame={f} listening={listening}/><h2>{listening?'I am listening':'What can I help with?'}</h2>{typed&&<div className="rf-spoken">{typed}</div>}</div>:<div className="rf-conversation" style={{opacity:ease(f,resultAt,resultAt+10)}}><div className="rf-user-bubble">{request}</div><p>I have drafted a template for you.</p><div className="rf-template"><h3>Seller follow-up</h3><p>Hi {'{{name}}'},</p><p>Recent sales in {'{{building}}'}:</p><p className="rf-variable">{'{{transactions}}'}</p><p>Thinking of selling?</p><div className="rf-confirm" style={{background:saved?'#c4d4b7':undefined}}>{saved?<><IconCheck size={24}/>Template saved</>:'Confirm change'}{f>=saveAt-12&&f<saveAt+8&&<span className="rf-confirm-touch" style={{opacity:1-ease(f,saveAt,saveAt+8),transform:`scale(${ease(f,saveAt-12,saveAt+8,.6,1.4)})`}}/>}</div>{!saved&&<div className="rf-discard">Discard</div>}</div></div>}<div className="rf-assistant-composer"><div>Message Repeat</div><span className={listening?'rf-voice-active':''}>{listening?<IconPlayerStopFilled size={24}/>:<IconWaveSine size={30}/>}</span></div>{f>=tap-9&&f<tap+12&&<div className="rf-touch" style={{opacity:1-ease(f,tap,tap+12),transform:`scale(${ease(f,tap-9,tap+12,.65,1.5)})`}}/>}</Phone></Base>}
function Integrations({row}:{row:Row}){const f=useCurrentFrame(),q=f/row.frames;return <Base><div className="rf-wide-heading"><span className="rf-eyebrow">Bring your tools along</span><h1>Connected to your work.</h1></div><div className="rf-integrations"><div className="rf-integration-row" style={{opacity:1-ease(q,.42,.51),transform:`translateY(${ease(q,.42,.51,0,-18)}px)`}}><div><IconBrandGmail size={98} stroke={1.45}/><span>Gmail</span></div><div><Img src={asset('workflow/outlook.svg')}/><span>Outlook</span></div><div><IconCalendar size={98} stroke={1.5}/><span>Calendar</span></div></div><div className="rf-integration-row rf-ai-row" style={{opacity:ease(q,.46,.57),transform:`translateY(${ease(q,.46,.6,18,0)}px)`}}><div><IconBrandOpenai size={108} stroke={1.4}/><span>ChatGPT</span></div><div><Img src={asset('workflow/polished/claude.svg')}/><span>Claude</span></div></div><svg className="rf-connectors" width="1100" height="330" viewBox="0 0 1100 330"><path d={q<.5?'M150 0V85Q150 105 175 105H525Q550 105 550 135V240M550 0V240M950 0V85Q950 105 925 105H575Q550 105 550 135':'M270 0V85Q270 105 295 105H525Q550 105 550 135V240M830 0V85Q830 105 805 105H575Q550 105 550 135'} fill="none" stroke="#a6b49c" strokeWidth="3"/></svg><div className="rf-repeat-hub"><Img src={asset('logo.png')}/></div></div><div className="rf-integration-caption">{q<.5?'Read your inbox. Check upcoming events.':'Find your sellers through ChatGPT or Claude.'}</div></Base>}
function Platforms(){return <Base><OffthreadVideo src={asset('desk-film.mp4')} muted style={{width:'100%',height:'100%',objectFit:'cover'}}/><div className="rf-platform-label">At your desk. On your phone.</div></Base>}
function Shot({row}:{row:Row}){switch(row.id){case'opening':return <Opening row={row}/>;case'brand':return <Brand/>;case'import':return <Import row={row}/>;case'seller':return <Seller row={row}/>;case'whatsapp':return <WhatsApp row={row}/>;case'schedule':return <Schedule row={row}/>;case'market':return <Market row={row}/>;case'assistant':return <Assistant row={row}/>;case'integrations':return <Integrations row={row}/>;case'platforms':return <Platforms/>;default:return <Brand close/>}}
function Layer({row,first}:{row:Row;first:boolean}){const f=useCurrentFrame();return <AbsoluteFill style={{opacity:first?1:ease(f,0,14),transform:`translateY(${first?0:ease(f,0,18,12,0)}px)`}}><Shot row={row}/></AbsoluteFill>}
export function RefinedFilm(){return <AbsoluteFill className="refined-film"><Audio src={asset('mix.wav')}/>{timeline.scenes.map((row,i)=><Sequence key={row.id} from={row.fromFrame} durationInFrames={row.frames+(i<timeline.scenes.length-1?18:0)}><Layer row={row as Row} first={i===0}/></Sequence>)}</AbsoluteFill>}
