import React from 'react';
import {AbsoluteFill, useCurrentFrame} from 'remotion';
import {IconMenu2, IconHome, IconUsers, IconDownload, IconSun, IconChevronDown, IconTable, IconFlame, IconClock, IconSearch, IconPlus, IconX, IconBrandWhatsapp, IconLink, IconFileSpreadsheet, IconCalendar} from '@tabler/icons-react';
import LeadCard from '../../../src/features/seller-signal/components/LeadCard';
import {OverviewPanel, MarketPanel, MessagePanel} from '../../../src/features/seller-signal/components/LeadModalPanels';
import {buildMessage} from '../../../src/features/seller-signal/insight-utils';
import {tween, pos, Cursor, Caption, Focus} from './primitives';

const noop=()=>{};
// Fictional example contacts. The UK 07700 900xxx range is reserved for drama.
export const leads=[
 ['Alex Morgan','The St. Regis Residences, Downtown Dubai','Prospect','1204',2],
 ['Maya Bennett','IMPERIAL AVENUE','For Sale Available','1802',2],
 ['Sam Carter','Burj Khalifa','Market Appraisal','2601',2],
 ['Jordan Hayes','Act towers 1','Prospect','902',1],
 ['Riley Brooks','Act tower 2','For Sale Available','1403',2],
 ['Taylor Reed','Burj Vista 1, Downtown Dubai','Market Appraisal','704',1],
 ['Casey Lane','Burj Vista 2, Downtown Dubai','Prospect','1601',2],
 ['Jamie Quinn','St Regis tower 2','Market Appraisal','1105',2],
].map(([name,building,statusLabel,unit,bedroom],i)=>({id:`demo-${i}`,name,building,statusLabel,status:statusLabel,unit,bedroom,phone:`+44 7700 90010${i}`,isDue:true,dueLabel:'Due today',dataQuality:{level:'trusted',label:'Complete',issues:[]}}));
export const marketInsight={status:'ready',locationName:'The St. Regis Residences, Downtown Dubai',count:5,avg:4473378,psf:3617,min:2500000,max:6300000,recentTransactions:[{id:'public-sale-1',date:'2026-09-21',locationLabel:'The St. Regis Residences, Downtown Dubai',price:6300000,beds:2,area:1323},{id:'public-sale-2',date:'2026-09-18',locationLabel:'The St. Regis Residences, Downtown Dubai',price:5336888,beds:2,area:1349}]};

export function AppHeader({page}:{page:string}){return <header className="wf-app-header"><IconMenu2 size={22}/><IconHome size={18}/><span>/</span>{page==='Sellers'?<IconUsers size={18} color="#9388cf"/>:page==='Schedule'?<IconCalendar size={18}/>:<IconTable size={18} color="#72b89b"/>}<strong>{page}</strong><div style={{marginLeft:'auto',display:'flex',gap:20,alignItems:'center'}}><button className="wf-download"><IconDownload size={18}/>Download app</button><IconSun size={18}/></div></header>}
function SourceBar(){return <div className="source-tabs-row" style={{marginBottom:24}}><button className="source-picker-btn"><IconTable size={16}/>Downtown leads<IconChevronDown size={16}/></button><button className="btn-sm btn-primary">＋ Add seller</button></div>}
function Toolbar({filter,count}:{filter:string;count:number}){return <><div className="toolbar seller-viewbar"><div className="toolbar-row seller-viewbar-row"><button className="seller-view-picker"><IconTable size={18}/>Saved views<IconChevronDown size={16}/></button><div className="seller-view-tabs"><button className="seller-view-tab is-active"><IconFlame size={16}/>Due today <span className="seller-view-tab-count">8</span></button><button className="seller-view-tab"><IconClock size={16}/>Scheduled <span className="seller-view-tab-count">0</span></button></div><div className="seller-filter-chips">{['Prospects','Appraisals','For sale','Not interested'].map(x=><button key={x} className={`seller-filter-chip${filter===x?' is-active':''}`}>{x}</button>)}<span className="seller-filter-separator"/><button className="seller-filter-chip">Needs review</button><button className="seller-filter-chip">Has market data</button></div></div><div className="wf-search">Search sellers<IconSearch size={17}/></div></div><div className="seller-record-meta">{count} leads</div></>}
export function SellerTable({filter='',hot=false}:{filter?:string;hot?:boolean}){
 const shown=leads.filter(l=>!filter||(filter==='Prospects'?l.statusLabel==='Prospect':filter==='For sale'?l.statusLabel==='For Sale Available':true));
 return <main style={{...pos(390,80),width:1140}}><SourceBar/><div className="seller-record-surface"><Toolbar filter={filter} count={shown.length}/><div className="lead-table-wrap"><table className="lead-table"><thead><tr>{['Name','Building','Bed','Unit','Status','Phone','Contact'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{shown.map((lead,i)=><LeadCard key={lead.id} lead={lead} hot={hot&&lead.id==='demo-0'} insight={{...marketInsight,locationName:lead.building,hasTodaysTransactions:hot&&lead.id==='demo-0'}} isSent={false} whatsappConnected={true} onToggleExpanded={noop} onToggleFavorite={noop} onTogglePin={noop}/>)}</tbody></table></div></div></main>
}
function SellerModal({section}:{section:'Overview'|'Market data'|'Message'}){const action=<button className="lead-modal-wa-btn"><IconBrandWhatsapp size={18}/>Send via WhatsApp</button>;return <div className="lead-modal-backdrop" style={{paddingTop:115}}><div className="lead-modal lead-detail-modal" style={{transform:'scale(1.32)',transformOrigin:'top center'}}><div className="lead-detail-header"><span className="lead-detail-header-icon">A</span><div className="lead-detail-header-title"><h2 className="lead-detail-name">Alex Morgan</h2><span className="lead-detail-building">The St. Regis Residences, Downtown Dubai</span></div><div className="lead-detail-header-actions"><button className="btn-sm">Edit</button><button className="lead-detail-close"><IconX size={16}/></button></div></div><ul className="lead-detail-sections">{['Overview','Market data','Message','Notes'].map(t=><li key={t}><button className={`lead-detail-section${section===t?' active':''}`}>{t}</button></li>)}</ul><div className="lead-detail-body"><div className="lead-detail-content">{section==='Overview'?<OverviewPanel action={action} lead={leads[0]} bedroomLabel="2 bed" unitLabel="Unit 1204"/>:section==='Market data'?<MarketPanel lead={leads[0]} insight={marketInsight}/>:<MessagePanel edited={false} message={buildMessage(leads[0],marketInsight)} selectedTemplateId="default" templateOptions={[{id:'default',label:'Default script'}]} whatsappConnected={true} onChangeMessage={noop}/>}</div></div>{section!=='Overview'&&<div className="lead-detail-footer">{action}</div>}</div></div>}
export function Sellers(){const f=useCurrentFrame();const filter=f>=180&&f<270?'Prospects':f>=270&&f<360?'For sale':'';const open=f>=540;const section=f<660?'Overview':f<870?'Market data':'Message';return <AbsoluteFill className="app-shell"><AppHeader page="Sellers"/><Focus scale={open?1:1.18} x={960} y={open?540:470}><SellerTable filter={filter} hot={f>=390}/></Focus>{!open&&f>=390&&<div className="floating-action-container" style={{bottom:100}}><button className="btn-floating-wa"><IconBrandWhatsapp size={24}/><div className="btn-floating-text"><span className="btn-floating-title">Send automated messages</span><span className="btn-floating-subtitle">8 ready on current page</span></div></button></div>}
 {f>=140&&f<300&&<Cursor x={f<250?tween(f,140,175,1050,875):tween(f,250,270,875,1095)} y={183} click={f<250?tween(f,178,180):tween(f,268,270)}/>}
 {f>=460&&f<550&&<Cursor x={tween(f,460,535,1050,460)} y={tween(f,460,535,355,399)} click={tween(f,537,540)}/>}
 {open&&<SellerModal section={section as any}/>}
 {f>=615&&f<675&&<Cursor x={tween(f,615,655,810,610)} y={232} click={tween(f,658,660)}/>}
 {f>=825&&f<885&&<Cursor x={tween(f,825,865,920,737)} y={232} click={tween(f,868,870)}/>}
 <Caption>{f<390?'Your sellers, organised by status.':f<540?'Fresh building sales give your follow-up context.':f<870?'Open a seller to see the building’s latest transactions.':'Personalised follow-ups, with WhatsApp connected.'}</Caption>
 </AbsoluteFill>}

export function ImportScene(){const f=useCurrentFrame();const mode=f<105?'choice':f<205?'url':f<235?'choice':f<365?'file':'complete';const chosen=f>=280;return <AbsoluteFill className="app-shell"><AppHeader page="Spreadsheets"/>
 {mode==='complete'?<div style={{...pos(390,155),width:1140}}><div className="wf-search" style={{marginBottom:50}}>Search spreadsheets<IconSearch size={18}/></div><div className="wf-imported-row"><IconFileSpreadsheet size={25}/><span>Downtown leads</span><span style={{marginLeft:'auto',color:'var(--text-muted)'}}>8 sellers</span><span>☆</span><span>•••</span></div><div style={{...pos(0,230),fontSize:28,color:'var(--text-muted)',opacity:tween(f,375,400)}}>Next: open Sellers</div></div>:<div style={{...pos(480,210),width:640,transform:'scale(1.5)',transformOrigin:'top left'}}><div className="lead-modal new-sheet-modal" style={{maxHeight:650}}><div className="lead-modal-header"><div className="lead-modal-title-block">{mode!=='choice'&&<button className="new-sheet-back">←</button>}<h2 className="lead-modal-name">{mode==='choice'?'Add a spreadsheet':mode==='url'?'From a Google Sheet URL':'Import Excel (.xlsx)'}</h2></div><button className="lead-modal-close"><IconX size={16}/></button></div><div className="lead-modal-body">
 {mode==='choice'?<div className="new-sheet-choice">{[['URL to spreadsheet','Paste a Google Sheet link.',IconLink],['Import Excel (.xlsx)','Upload an Excel or CSV file.',IconFileSpreadsheet]].map(([title,desc,Icon])=><button key={title as string} className="new-sheet-choice-card"><span className="new-sheet-choice-icon">{React.createElement(Icon as any,{size:22})}</span><span className="new-sheet-choice-text"><span className="new-sheet-choice-title">{title as string}</span><span className="new-sheet-choice-desc">{desc as string}</span></span></button>)}</div>:mode==='url'?<div className="new-sheet-form"><div className="new-sheet-input-row"><input className="new-sheet-url" readOnly value={'https://docs.google.com/spreadsheets/d/your-sheet'.slice(0,Math.round(tween(f,115,195,0,50)))} placeholder="Paste your Google Sheet link"/><button className="new-sheet-submit"><IconPlus size={18}/></button></div><div className="new-sheet-instructions"><h3 className="new-sheet-instructions-title">How to get your spreadsheet link</h3><ol className="new-sheet-steps">{[<>Open your sheet at <strong>sheets.google.com</strong> (or upload an Excel file via <strong>File → Import</strong>).</>,<>Click <strong>Share</strong> in the top right and set access to <em>Anyone with the link</em>.</>,<>Copy the URL from your browser’s address bar and paste it above.</>].map((x,i)=><li key={i}><span className="new-sheet-step-num">{i+1}</span><span className="new-sheet-step-text">{x}</span></li>)}</ol></div></div>:<div className="new-sheet-form"><p className="new-sheet-picture-hint">Import sellers from Excel or CSV. One worksheet, up to 10 MB.</p><div className="new-sheet-input-row" style={{marginTop:10}}><div style={{fontSize:13,display:'flex',alignItems:'center',gap:6,flex:1}}><span style={{border:'1px solid #aaa',borderRadius:2,background:'#777',color:'#fff',padding:'2px 6px'}}>Choose file</span><span style={{color:'var(--text-muted)'}}>{chosen?'Downtown-leads.xlsx':'No file chosen'}</span></div><button className="btn-sm btn-primary" disabled={!chosen}>{f>=342?'Importing…':'Import'}</button></div></div>}
 </div></div></div>}
 {f>=75&&f<115&&<Cursor x={tween(f,75,100,1430,1040)} y={385} click={tween(f,102,105)}/>}
 {f>=185&&f<205&&<Cursor x={tween(f,185,200,1030,515)} y={255} click={tween(f,202,205)}/>}
 {f>=210&&f<240&&<Cursor x={tween(f,210,230,515,1000)} y={480} click={tween(f,232,235)}/>}
 {f>=255&&f<285&&<Cursor x={tween(f,255,275,1000,560)} y={395} click={tween(f,277,280)}/>}
 {f>=315&&f<365&&<Cursor x={tween(f,315,340,930,1365)} y={395} click={tween(f,340,343)}/>}
 <Caption>{mode==='complete'?'Your imported leads are ready in the workspace.':'Import through a Google Sheet URL or an Excel file.'}</Caption>
 </AbsoluteFill>}
