import React from 'react';
import {AbsoluteFill, useCurrentFrame} from 'remotion';
import {IconBuildingEstate, IconMenu2, IconHome, IconUsers, IconDownload, IconSun, IconChevronDown, IconTable, IconFlame, IconClock, IconSearch, IconX, IconBrandWhatsapp, IconCalendar} from '@tabler/icons-react';
import LeadCard from '../../../src/features/seller-signal/components/LeadCard';
import {OverviewPanel, MarketPanel, MessagePanel} from '../../../src/features/seller-signal/components/LeadModalPanels';
import {buildMessage} from '../../../src/features/seller-signal/insight-utils';
import {tween, pos, Cursor, Focus} from './primitives';

const noop=()=>{};
// Fictional example contacts. The UK 07700 900xxx range is reserved for drama.
export const leads=[
 ['Alex Morgan','The St. Regis Residences, Downtown Dubai','Prospect','1204',2],
 ['Maya Bennett','The St. Regis Residences, Downtown Dubai','For Sale Available','1802',2],
 ['Sam Carter','The St. Regis Residences, Downtown Dubai','Market Appraisal','2601',2],
 ['Jordan Hayes','The St. Regis Residences, Downtown Dubai','Prospect','902',1],
 ['Riley Brooks','Burj Khalifa','For Sale Available','1403',2],
 ['Taylor Reed','Burj Khalifa','Market Appraisal','704',1],
 ['Casey Lane','Burj Khalifa','Prospect','1601',2],
 ['Jamie Quinn','Burj Khalifa','Market Appraisal','1105',2],
].map(([name,building,statusLabel,unit,bedroom],i)=>({id:`demo-${i}`,name,building,statusLabel,status:statusLabel,unit,bedroom,phone:`+44 7700 90010${i}`,isDue:true,dueLabel:'Due today',dataQuality:{level:'trusted',label:'Complete',issues:[]}}));
export const marketInsight={status:'ready',locationName:'The St. Regis Residences, Downtown Dubai',count:5,avg:4473378,psf:3617,min:2500000,max:6300000,recentTransactions:[{id:'public-sale-1',date:'2026-09-21',locationLabel:'The St. Regis Residences, Downtown Dubai',price:6300000,beds:2,area:1323},{id:'public-sale-2',date:'2026-09-18',locationLabel:'The St. Regis Residences, Downtown Dubai',price:5336888,beds:2,area:1349}]};

export function AppHeader({page}:{page:string}){return <header className="wf-app-header"><IconMenu2 size={22}/><IconHome size={18}/><span>/</span>{page==='Sellers'?<IconUsers size={18} color="#9388cf"/>:page==='Listings'?<IconBuildingEstate size={18}/>:page==='Schedule'?<IconCalendar size={18}/>:<IconTable size={18} color="#72b89b"/>}<strong>{page}</strong><div style={{marginLeft:'auto',display:'flex',gap:20,alignItems:'center'}}><button className="wf-download"><IconDownload size={18}/>Download app</button><IconSun size={18}/></div></header>}
function SourceBar(){return <div className="source-tabs-row" style={{marginBottom:24}}><button className="source-picker-btn"><IconTable size={16}/>All spreadsheets<IconChevronDown size={16}/></button><button className="btn-sm btn-primary">＋ Add seller</button></div>}
function Toolbar({filter,count}:{filter:string;count:number}){return <><div className="toolbar seller-viewbar"><div className="toolbar-row seller-viewbar-row"><button className="seller-view-picker"><IconTable size={18}/>Saved views<IconChevronDown size={16}/></button><div className="seller-view-tabs"><button className="seller-view-tab is-active"><IconFlame size={16}/>Due today <span className="seller-view-tab-count">8</span></button><button className="seller-view-tab"><IconClock size={16}/>Scheduled <span className="seller-view-tab-count">0</span></button></div><div className="seller-filter-chips">{['Prospects','Appraisals','For sale','Not interested'].map(x=><button key={x} className={`seller-filter-chip${filter===x?' is-active':''}`}>{x}</button>)}<span className="seller-filter-separator"/><button className="seller-filter-chip">Needs review</button><button className="seller-filter-chip">Has market data</button></div></div><div className="wf-search">Search sellers<IconSearch size={17}/></div></div><div className="seller-record-meta">{count} leads</div></>}
export function SellerTable({filter='',hot=false}:{filter?:string;hot?:boolean}){
 const shown=leads.filter(l=>!filter||(filter==='Prospects'?l.statusLabel==='Prospect':filter==='For sale'?l.statusLabel==='For Sale Available':true));
 return <main style={{...pos(390,80),width:1140}}><SourceBar/><div className="seller-record-surface"><Toolbar filter={filter} count={shown.length}/><div className="lead-table-wrap"><table className="lead-table"><thead><tr>{['Name','Building','Bed','Unit','Status','Phone','Contact'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{shown.map(lead=><LeadCard key={lead.id} lead={lead} hot={hot&&lead.id==='demo-0'} insight={{...marketInsight,locationName:lead.building,hasTodaysTransactions:hot&&lead.id==='demo-0'}} isSent={false} whatsappConnected={true} onToggleExpanded={noop} onToggleFavorite={noop} onTogglePin={noop}/>)}</tbody></table></div></div></main>
}
function SellerModal({section}:{section:'Overview'|'Market data'|'Message'}){const action=<button className="lead-modal-wa-btn"><IconBrandWhatsapp size={18}/>Send via WhatsApp</button>;return <div className="lead-modal-backdrop" style={{paddingTop:115}}><div className="lead-modal lead-detail-modal" style={{transform:'scale(1.32)',transformOrigin:'top center'}}><div className="lead-detail-header"><span className="lead-detail-header-icon">A</span><div className="lead-detail-header-title"><h2 className="lead-detail-name">Alex Morgan</h2><span className="lead-detail-building">The St. Regis Residences, Downtown Dubai</span></div><div className="lead-detail-header-actions"><button className="btn-sm">Edit</button><button className="lead-detail-close"><IconX size={16}/></button></div></div><ul className="lead-detail-sections">{['Overview','Market data','Message','Notes'].map(t=><li key={t}><button className={`lead-detail-section${section===t?' active':''}`}>{t}</button></li>)}</ul><div className="lead-detail-body"><div className="lead-detail-content">{section==='Overview'?<OverviewPanel action={action} lead={leads[0]} bedroomLabel="2 bed" unitLabel="Unit 1204"/>:section==='Market data'?<MarketPanel lead={leads[0]} insight={marketInsight}/>:<MessagePanel edited={false} message={buildMessage(leads[0],marketInsight)} selectedTemplateId="default" templateOptions={[{id:'default',label:'Default script'}]} whatsappConnected={true} onChangeMessage={noop}/>}</div></div>{section!=='Overview'&&<div className="lead-detail-footer">{action}</div>}</div></div>}
export function Sellers(){const f=useCurrentFrame()*37/28;const filter=f>=180&&f<270?'Prospects':f>=270&&f<360?'For sale':'';const open=f>=540;const section=f<660?'Overview':f<870?'Market data':'Message';return <AbsoluteFill className="app-shell"><AppHeader page="Sellers"/><Focus scale={open?1:1.18} x={960} y={open?540:470}><SellerTable filter={filter} hot={f>=390}/></Focus>{!open&&f>=390&&<div className="floating-action-container" style={{bottom:100}}><button className="btn-floating-wa"><IconBrandWhatsapp size={24}/><div className="btn-floating-text"><span className="btn-floating-title">Send automated messages</span><span className="btn-floating-subtitle">8 ready on current page</span></div></button></div>}
 {f>=140&&f<300&&<Cursor x={f<250?tween(f,140,175,1050,875):tween(f,250,270,875,1095)} y={183} click={Math.max(0,1-Math.abs(f-(f<250?180:270))/5)}/>}
 {f>=460&&f<540&&<Cursor x={tween(f,460,535,1050,460)} y={tween(f,460,535,355,399)} click={Math.max(0,1-Math.abs(f-535)/5)}/>}
 {open&&<SellerModal section={section as any}/>}
 {f>=615&&f<675&&<Cursor x={tween(f,615,655,810,610)} y={232} click={Math.max(0,1-Math.abs(f-660)/5)}/>}
 {f>=825&&f<885&&<Cursor x={tween(f,825,865,920,737)} y={232} click={Math.max(0,1-Math.abs(f-870)/5)}/>}

 </AbsoluteFill>}
