import React from 'react';
import {AbsoluteFill, Img, staticFile, useCurrentFrame} from 'remotion';
import {Broker} from './RepeatAIIllustratedOpening';

const cream='#f6f2e9', ink='#242424', orange='#ef966b';
export const story = [
  ['00–04','The broker’s problem','Your sellers. Your spreadsheets. A market that never stops.','The broker’s loose seller row moves into the next frame.'],
  ['04–10','All your spreadsheets, together','Keep all your spreadsheets together. Bring your sellers into one organised workspace.','Multiple spreadsheet sources collect together; Sara’s row opens.'],
  ['10–16','See what changed','Monitor listings and price changes in the buildings you cover.','The building label carries across into Sara’s market data.'],
  ['16–22','Give the seller useful context','See recent sales in their building, so your follow-up has a reason.','One transaction line travels into the message template.'],
  ['22–28','Personalise before sending','Personalise your template. Then send through your connected WhatsApp.','The same text moves from the editor into WhatsApp.'],
  ['28–36','Show the actual conversation','A relevant update. A more useful conversation.','Read the message; a fictional reply arrives near 34 seconds.'],
  ['36–42','Automate the daily follow-up','Automate up to fifty seller follow-ups a day. Keep your pipeline moving.','PROPOSED 50/day claim: current worker caps at 40; reconcile before release.'],
  ['42–48','Sell the outcome','Less admin. More informed follow-ups. Repeat AI. Seller follow-up, done properly.','Return to the same broker, then hold the wordmark and CTA.'],
];
const art=(name:string)=>staticFile(`video/repeat-ai-v4/${name}.png`);
const label:React.CSSProperties={fontSize:15,letterSpacing:2,textTransform:'uppercase',color:'#777168'};
const box:React.CSSProperties={background:'#fffdf9',border:'1px solid #d9d3c8',borderRadius:14,padding:24};
const Pill:React.FC<React.PropsWithChildren>=({children})=><span style={{background:'#f6ddce',padding:'8px 13px',borderRadius:7,fontSize:17}}>{children}</span>;
const Header:React.FC<{title:string}>=({title})=><div style={{position:'absolute',top:34,left:44,right:44,display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontWeight:700,fontSize:23}}>Repeat AI</span><span style={{fontSize:18,color:'#777168'}}>{title}</span></div>;
const message=<>Hi Sara, a recent sale in Marina Tower:<br/><br/>2 bed · 1,410 sq ft · AED 2.4M<br/><br/>Want to discuss how yours compares?</>;
export const StoryFrame:React.FC<{index:number}>=({index})=><AbsoluteFill style={{background:cream,color:ink,fontFamily:'Arial, sans-serif',overflow:'hidden'}}>
  <div style={{position:'absolute',bottom:12,right:22,fontSize:12,color:'#777168'}}>STORYBOARD · ILLUSTRATIVE DATA / SIMPLIFIED UI</div>
  {index===0 && <><div style={{position:'absolute',left:55,top:60,fontSize:39,lineHeight:1.1}}>Too many places.<br/>Too much to remember.</div><div style={{position:'absolute',left:360,top:110,width:400,height:400}}><Broker frame={24}/></div><Img src={art('notes')} style={{position:'absolute',left:50,top:235,width:230}}/><Img src={art('property')} style={{position:'absolute',right:20,top:50,width:215}}/><div style={{...box,position:'absolute',left:66,top:428,padding:14,fontSize:18,transform:'rotate(-4deg)'}}>Sara · Marina Tower · Follow up</div></>}
  {index===1 && <><Header title="Spreadsheets → Sellers"/><div style={{position:'absolute',left:48,top:120,width:265}}><div style={label}>Your spreadsheets</div>{['Marina sellers.xlsx','Downtown owners.csv','Palm contacts.xlsx'].map((name,i)=><div key={name} style={{...box,marginTop:18,padding:20,fontSize:20,transform:`rotate(${[ -3,2,-1][i]}deg)`}}>{name}</div>)}</div><div style={{position:'absolute',left:326,top:264,fontSize:36}}>→</div><div style={{...box,position:'absolute',left:388,top:120,width:476}}><div style={label}>One organised workspace</div><h2 style={{fontSize:30}}>All your spreadsheets, together.</h2>{['Sara  /  Marina Tower','Adam  /  Creek View','Maya  /  Palm Court'].map((s,i)=><div key={s} style={{padding:'20px 12px',borderTop:'1px solid #e5dfd6',background:i===0?'#f6ddce':undefined,fontSize:21}}>{s}</div>)}</div></>}
  {index===2 && <><Header title="Listings"/><div style={{position:'absolute',left:52,top:120}}><div style={label}>Watched building</div><h1 style={{fontSize:40}}>Marina Tower</h1><div style={{display:'flex',gap:12}}><Pill>New listings</Pill><Pill>Price drops</Pill><Pill>Status changes</Pill></div><div style={{...box,width:510,marginTop:30,fontSize:25}}>2 bedroom · Listing update<div style={{marginTop:24,color:'#898176',textDecoration:'line-through'}}>AED 2,600,000</div><div style={{marginTop:9,fontWeight:700}}>AED 2,470,000 <span style={{color:'#b45d30',fontSize:20}}>−5%</span></div></div></div><Img src={art('property')} style={{position:'absolute',right:30,top:153,width:295}}/></>}
  {index===3 && <><Header title="Sellers / Sara / Market data"/><div style={{...box,position:'absolute',left:50,top:123,width:260}}><div style={label}>Seller</div><h1>Sara</h1><p style={{fontSize:23}}>Marina Tower · 2 bed</p><Pill>Prospect</Pill></div><div style={{...box,position:'absolute',left:396,top:123,width:468}}><div style={label}>Sales history in Marina Tower</div><h2 style={{fontSize:30}}>A reason to reach out.</h2><div style={{background:'#f6ddce',padding:22,fontSize:24,lineHeight:1.6}}>Recent sale<br/><strong>AED 2,400,000</strong><br/>2 bed · 1,410 sq ft</div></div><div style={{position:'absolute',left:50,top:422,fontSize:20,color:'#777168'}}>Listing changes and completed transactions are separate data.</div></>}
  {index===4 && <><Header title="Sara / Message"/><div style={{...box,position:'absolute',left:60,top:109,width:786}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><Pill>Template: Transaction update</Pill><span style={{fontSize:17}}>WhatsApp connected</span></div><div style={{border:'1px solid #ddd5c9',padding:23,marginTop:20,fontSize:24,lineHeight:1.35}}>{message}<span style={{color:'#b45d30'}}>│</span></div><div style={{display:'flex',justifyContent:'space-between',marginTop:22,alignItems:'center'}}><span style={{fontSize:17}}>Editable for this seller</span><span style={{background:ink,color:cream,padding:'13px 20px',borderRadius:8,fontSize:20}}>Send via WhatsApp</span></div></div></>}
  {index===5 && <><div style={{position:'absolute',left:44,top:63,width:260}}><div style={label}>WhatsApp</div><h1 style={{fontSize:39,lineHeight:1.13}}>A relevant update.<br/>Not “just checking in”.</h1><p style={{fontSize:19,color:'#777168',lineHeight:1.5}}>Same message.<br/>Realistic chat layout.<br/>Fictional example reply.</p></div><div style={{position:'absolute',left:355,top:25,width:540,height:474,border:'2px solid #d5cec0',borderRadius:24,overflow:'hidden',background:'#ebe6db'}}><div style={{background:'#fffdf9',padding:'18px 22px',fontSize:22}}>‹　●　Sara <span style={{float:'right'}}>Call　⋮</span></div><div style={{textAlign:'center',fontSize:13,color:'#777168',marginTop:13}}>TODAY</div><div style={{background:'#dceccd',margin:'14px 18px 0 67px',padding:20,borderRadius:'13px 0 13px 13px',fontSize:21,lineHeight:1.3}}>{message}<div style={{textAlign:'right',fontSize:12,marginTop:8,color:'#60755a'}}>10:24　✓✓</div></div><div style={{background:'#fffdf9',margin:'16px 95px 0 18px',padding:15,borderRadius:'0 13px 13px 13px',fontSize:21}}>Yes, can we talk this afternoon?<div style={{fontSize:12,marginTop:7,color:'#777168'}}>10:25</div></div></div></>}
  {index===6 && <><Header title="Daily WhatsApp automation"/><div style={{position:'absolute',left:55,top:128,width:480}}><div style={label}>Automate seller follow-ups</div><div style={{fontSize:105,fontWeight:700,marginTop:13,lineHeight:1}}>Up to 50</div><div style={{fontSize:37,marginTop:15}}>seller follow-ups a day.</div><div style={{fontSize:22,color:'#777168',marginTop:24}}>Your template. Relevant market context.</div></div><div style={{...box,position:'absolute',left:605,top:122,width:245}}><Pill>Automatic follow-up</Pill>{['Eligible seller','Market update','Your saved template','Connected WhatsApp'].map(s=><div key={s} style={{padding:'21px 0',fontSize:21,borderBottom:'1px solid #e5dfd6'}}>{s}</div>)}</div><div style={{position:'absolute',left:55,top:427,right:50,fontSize:18,color:'#9a522f',lineHeight:1.4}}>PROPOSED COPY — database history allows 50/day; current worker caps at 40.<br/>Reconcile before release. Sending depends on eligibility and available data.</div></>}
  {index===7 && <><div style={{position:'absolute',left:15,top:115,width:405,height:405}}><Broker frame={26}/></div><div style={{position:'absolute',left:453,top:135}}><div style={{fontSize:45,fontWeight:700}}>Repeat AI</div><div style={{fontSize:34,lineHeight:1.2,marginTop:24}}>Seller follow-up,<br/>done properly.</div><div style={{marginTop:28,fontSize:20,color:'#777168'}}>Sellers. Market context. WhatsApp.</div><div style={{background:ink,color:cream,padding:'16px 23px',borderRadius:9,marginTop:28,display:'inline-block',fontSize:22}}>Get started with Repeat AI</div></div></>}
</AbsoluteFill>;

export const RepeatAIStoryboardFrame:React.FC=()=> <StoryFrame index={Math.min(7,useCurrentFrame())}/>;
export const RepeatAIStoryboardBoard:React.FC=()=> <AbsoluteFill style={{background:'#e7e1d6',fontFamily:'Arial, sans-serif',color:ink,padding:40}}>
  <div style={{height:120}}><div style={{fontSize:48,fontWeight:700}}>Repeat AI / Product-first storyboard</div><div style={{fontSize:23,marginTop:14}}>48 seconds · cream, charcoal, warm orange · Sunlit Walkthrough · green reserved for WhatsApp</div></div>
  <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:32}}>{story.map((s,i)=><div key={s[0]} style={{height:805}}><div style={{display:'flex',justifyContent:'space-between',fontSize:26,fontWeight:700,marginBottom:14}}><span>{i+1}. {s[1]}</span><span>{s[0]}</span></div><div style={{height:630,position:'relative',overflow:'hidden'}}><div style={{position:'absolute',width:960,height:540,transform:'scale(1.15)',transformOrigin:'top left'}}><StoryFrame index={i}/></div></div><div style={{fontSize:24,lineHeight:1.32,marginTop:12}}>VO: “{s[2]}”</div><div style={{fontSize:21,color:'#70695d',marginTop:10}}>Motion: {s[3]}</div></div>)}</div>
</AbsoluteFill>;
