import React from 'react';
import {AbsoluteFill, Easing, interpolate, useCurrentFrame} from 'remotion';
import {IconArrowLeft, IconBrandWhatsapp, IconBuildingEstate, IconCheck, IconChevronDown, IconHome, IconPlus, IconX} from '@tabler/icons-react';
import {ArrowUp, AudioLines, Plus, X} from 'lucide-react';
import {MarketPanel} from '../../../src/features/seller-signal/components/LeadModalPanels';
import {PriceChart, PriceDeltaChip} from '../../../src/features/listing-alerts/components/ListingDetailParts';
import '../../../src/styles/seller-panels.css';
import '../../../src/styles/seller-insights.css';
import '../../../src/styles/lead-modal.css';
import '../../../src/styles/lead-detail-modal.css';
import '../../../src/styles/listing-detail.css';
import '../../../src/styles/listing-detail-chart-first.css';
import '../../../src/features/schedule/schedule.css';
import '../../../src/voice/voice.css';
import './product.css';

const ease=(f:number,a:number,b:number,x=0,y=1)=>interpolate(f,[a,b],[x,y],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(.22,.75,.25,1)});
const stRegis='The St. Regis Residences, Downtown Dubai';
const buildings=[stRegis,'Burj Khalifa'];
const lead={name:'Alex Morgan',building:stRegis,statusLabel:'Prospect',unit:'1204',bedroom:2};
// Fictional contacts and illustrative transaction/asking-price data, never an account export.
const insight={status:'ready',locationName:stRegis,count:5,avg:4473378,psf:3617,min:2500000,max:6300000,recentTransactions:[{id:'example-1',date:'2026-09-21',locationLabel:stRegis,price:6300000,beds:2,area:1323},{id:'example-2',date:'2026-09-18',locationLabel:stRegis,price:5336888,beds:2,area:1349}]};
const history=[{at:'2026-09-02T12:00:00Z',price:6900000,type:'new'},{at:'2026-09-08T12:00:00Z',price:6900000,type:'tracked'},{at:'2026-09-14T12:00:00Z',price:6600000,type:'price_drop'},{at:'2026-09-18T12:00:00Z',price:6600000,type:'tracked'},{at:'2026-09-21T12:00:00Z',price:6300000,type:'price_drop'}];

function Pointer({x,y,click=0,opacity=1}:{x:number;y:number;click?:number;opacity?:number}){return <svg className="lp-pointer" style={{left:x,top:y,opacity,transform:`scale(${1-click*.16})`}} width="35" height="44" viewBox="0 0 28 36"><path d="M3 2L24 22L14.8 23.4L10.2 33L3 2Z" fill="#fff" stroke="#20201f" strokeWidth="1.8" strokeLinejoin="round"/></svg>}
function Topbar({page}:{page:string}){return <header className="lp-topbar"><IconHome size={20}/><span>/</span><span>{page}</span></header>}
function Shell({children,className=''}:{children:React.ReactNode;className?:string}){return <AbsoluteFill className={`launch-product app-shell ${className}`} data-theme="dark">{children}</AbsoluteFill>}
function click(f:number,at:number){return Math.max(0,1-Math.abs(f-at)/5)}

/** 210 frames: focus the actual seller record, reveal transaction, choose WhatsApp. */
export function SellerMoment({frameOverride}:{frameOverride?:number}={}){const current=useCurrentFrame();const f=frameOverride??current;const open=ease(f,0,23);const message=f>=158;
 return <Shell className="lp-seller"><Topbar page="Sellers"/><div className="lp-seller-record" style={{opacity:open,transform:`translateY(${(1-open)*60}px) scale(${ease(f,30,140,1,1.035)})`}}>
 <section className="lead-modal lead-detail-modal"><header className="lead-detail-header"><span className="lead-detail-header-icon">A</span><div className="lead-detail-header-title"><h2 className="lead-detail-name">Alex Morgan</h2><span className="lead-detail-building">{stRegis}</span></div><div className="lead-detail-header-actions"><button className="lp-edit">Edit</button><button className="lead-detail-close"><IconX size={16}/></button></div></header>
 <ul className="lead-detail-sections">{['Overview','Market data','Message','Notes'].map(name=><li key={name}><button className={`lead-detail-section ${name===(message?'Message':'Market data')?'active':''}`}>{name}</button></li>)}</ul>
 <div className="lead-detail-body"><div className="lead-detail-content">{message?<div className="lead-detail-panel lp-drafted-message" style={{opacity:ease(f,158,168)}}><div className="lead-detail-panel-head"><h3 className="lead-detail-panel-title">Message</h3><p className="lead-detail-panel-subtitle">Applies to this seller only - your saved templates stay unchanged.</p></div><div className="lead-message-editor">Hi Alex,<br/><br/>A 2-bed apartment in The St. Regis Residences has just sold for AED 6,300,000.<br/><br/>Would you like an updated valuation?</div></div>:<MarketPanel lead={lead} insight={insight}/>}</div></div>
 <footer className="lead-detail-footer"><button className="lead-modal-wa-btn" style={{boxShadow:f>180?`0 0 0 ${ease(f,180,205,0,5)}px #bac8a718`:undefined}}><IconBrandWhatsapp size={18}/>Send via WhatsApp</button></footer></section>
 </div><Pointer x={f<158?ease(f,110,153,1200,730):ease(f,168,197,730,1430)} y={f<158?ease(f,110,153,780,343):ease(f,168,197,343,990)} click={Math.max(click(f,157),click(f,201))} opacity={ease(f,108,120)}/></Shell>
}

/** 150 frames: the live product schedules buildings, not individual contacts. */
export function ScheduleMoment({frameOverride}:{frameOverride?:number}={}){const current=useCurrentFrame();const f=frameOverride??current;const picker=f>=18&&f<84;const chosen=f>=58;const saved=f>=127;const days=['Monday','Tuesday','Wednesday','Thursday','Friday'];const slots=[buildings,[buildings[1]],buildings,chosen?[buildings[0]]:[],[]];
 return <Shell className="lp-schedule"><Topbar page="Schedule"/><div className="lp-schedule-stage" style={{transform:`translateY(${ease(f,0,18,35,0)}px)`,opacity:ease(f,0,12)}}><main className="schedule-page"><header className="schedule-heading"><div className="schedule-heading-actions"><button className="schedule-save">{saved?<><IconCheck size={17}/> Saved</>:'Save'}</button></div></header><fieldset className="schedule-controls"><label className="schedule-enable"><input type="checkbox" checked readOnly/>Weekly schedule</label><div className="schedule-board">{days.map((day,i)=><section className="schedule-day" key={day}><h2>{day}</h2><div className="schedule-buildings">{slots[i].length?slots[i].map((building,j)=><div key={building} className="schedule-building" style={{opacity:i===3?ease(f,84,96):1,transform:i===3?`translateY(${ease(f,84,98,10,0)}px)`:undefined}}><span>{building}</span><button><IconX size={15}/></button></div>):<p className="schedule-off">No sends</p>}</div><button className="schedule-add"><IconPlus size={16}/>Add buildings</button></section>)}</div><label className="schedule-fallback"><input type="checkbox" checked={false} readOnly/>Fill unused slots from other buildings</label></fieldset>
 {picker&&<><div className="lp-picker-shade"/><div className="schedule-picker lp-schedule-picker" style={{opacity:ease(f,18,23),transform:`translateY(${ease(f,18,27,12,0)}px)`}}><header><h2>Thursday buildings</h2><button><IconX size={20}/></button></header><label className="schedule-source">Spreadsheet<div className="lp-source-control">{f<39?'Choose a spreadsheet':stRegis}<IconChevronDown size={17}/></div></label>{f>=23&&f<39&&<div className="lp-source-options"><div>{stRegis}</div><div>Burj Khalifa</div></div>}<input readOnly placeholder="Search spreadsheet buildings"/><div className="schedule-picker-list">{f<39?<p>Choose a spreadsheet to see its buildings.</p>:<label><input type="checkbox" checked={chosen} readOnly/><span>{stRegis}</span></label>}</div><button className="schedule-save">Done</button></div></>}
 </main></div><Pointer x={picker?(f<39?974:f<70?664:702):f<18?1275:ease(f,94,121,1220,1670)} y={picker?(f<39?450:f<70?525:609):f<18?654:ease(f,94,121,728,180)} click={Math.max(click(f,17),click(f,38),click(f,58),click(f,81),click(f,126))} opacity={f>135?ease(f,135,146,1,0):1}/></Shell>
}

/** 180 frames: actual listing chart and chip components; only the line reveal is choreographed. */
export function MarketMoment({frameOverride}:{frameOverride?:number}={}){const current=useCurrentFrame();const f=frameOverride??current;const reveal=interpolate(f,[27,123],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <Shell className="lp-market"><Topbar page="Listings"/><main className="ld-page ld-chart-first lp-listing" style={{opacity:ease(f,0,15),transform:`translateY(${ease(f,0,26,38,0)}px) scale(${ease(f,30,175,1,1.018)})`}}><div className="ld-scroll"><button className="ld-back-link"><IconArrowLeft size={20}/>Back to Burj Khalifa</button><div className="ld-summary"><div className="ld-heading"><h1 className="ld-title">Burj Khalifa</h1><p className="ld-area">Downtown Dubai · 2 beds · 1,639 sqft</p></div><div className="ld-actions"><button className="btn-sm">View listing ↗</button></div></div><div className="ld-price-toolbar"><div className="ld-price-hero"><div className="ld-price-row"><span className="ld-price-value">AED {f<88?'6,900,000':f<123?'6,600,000':'6,300,000'}</span><span style={{opacity:ease(f,123,133)}}><PriceDeltaChip priceDelta={-300000}/></span></div><p className="ld-price-prev" style={{opacity:ease(f,88,94)}}>Previous AED {f<123?'6,900,000':'6,600,000'}</p></div><div className="ld-tabs-wrap"><div className="ld-tabs"><button className="tab active">Price history</button><button className="tab">Activity</button></div></div></div><div className="ld-section ld-chart-section lp-price-drawing" style={{'--lp-chart-reveal':`${reveal*100}%`} as React.CSSProperties}><PriceChart priceHistory={history}/></div></div></main></Shell>}

function MatrixOrb({frame}:{frame:number}){return <svg width="148" height="148" className="assistant-matrix-orb">{Array.from({length:121},(_,i)=>{const x=i%11-5,y=Math.floor(i/11)-5,d=Math.hypot(x/5,y/5),r=6.5*Math.exp(-d*d*1.7)*(.64+.09*Math.sin(frame/29-d*2.4));return d<1.12?<circle key={i} cx={74+x*9.6} cy={74+y*9.6} r={r} fill="currentColor"/>:null})}</svg>}
const request='Create a follow-up template for my sellers.';
/** 240 frames: real current composer geometry (send inside, voice beside), typed request, review. */
export function AssistantMoment({frameOverride}:{frameOverride?:number}={}){const current=useCurrentFrame();const f=frameOverride??current;const sent=f>=106,review=f>=146;const typed=request.slice(0,Math.max(0,Math.floor((f-20)/1.65)));return <Shell className="lp-assistant"><div className="lp-assistant-title" style={{opacity:ease(f,0,22),transform:`translateY(${ease(f,0,25,26,0)}px)`}}>Ask<br/>Repeat.</div><div className="repeat-assistant is-open lp-assistant-position" style={{opacity:ease(f,0,18),transform:`translateY(${ease(f,0,22,35,0)}px) scale(1.58)`}}><section className="assistant-panel"><header className="assistant-header"><span>Repeat AI</span><div className="assistant-header-actions"><button><Plus size={26}/></button><button><X size={24}/></button></div></header><div className={`assistant-body ${!sent?'is-empty':''}`}>{!sent?<><MatrixOrb frame={f}/><h2>What can I help with?</h2></>:<><div className="assistant-chat-log"><p className="assistant-chat-message is-user">{request}</p><p className="assistant-chat-message is-assistant" style={{opacity:ease(f,115,126)}}>{review?'I’ve drafted a follow-up template. Review it before saving.':'Thinking…'}</p></div>{review&&<div className="assistant-approval" style={{opacity:ease(f,146,157),transform:`translateY(${ease(f,146,160,12,0)}px)`}}><h3>Create template “Seller follow-up”?</h3><p>{'Hi {{name}},\n\nHere are the latest sales in {{building}}:\n{{transactions}}\n\nWould you like an updated valuation?'}</p><button>Confirm change</button><button>Discard</button></div>}</>}</div><footer className="assistant-footer"><div className="assistant-composer"><div className="lp-composer-text">{!sent&&typed?<>{typed}<span className="lp-type-caret" style={{opacity:Math.floor(f/12)%2===0?1:0}}/></>:<span className="lp-placeholder">Message Repeat</span>}</div>{!sent&&typed&&<button aria-label="Send message"><ArrowUp size={22}/></button>}</div><button className="assistant-voice-toggle" aria-label="Start voice conversation" disabled={sent&&!review}><AudioLines size={24}/></button></footer></section></div>{f>=89&&f<116&&<Pointer x={ease(f,89,102,1330,1468)} y={923} click={click(f,106)}/>}</Shell>}
