create table if not exists public.buildings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  search_name text,
  location_name text,
  location_id integer,
  created_at timestamptz default timezone('utc', now())
);

alter table public.buildings
  add column if not exists key text,
  add column if not exists search_name text,
  add column if not exists location_name text,
  add column if not exists location_id integer,
  add column if not exists created_at timestamptz default timezone('utc', now());

create unique index if not exists buildings_key_key
  on public.buildings (key);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  building_key text not null,
  amount numeric,
  category text,
  date date,
  floor text,
  beds text,
  property_type text,
  builtup_area_sqft numeric,
  occupancy_status text,
  location_name text,
  full_location text,
  latitude numeric,
  longitude numeric,
  created_at timestamptz default timezone('utc', now())
);

alter table public.transactions
  add column if not exists building_key text,
  add column if not exists amount numeric,
  add column if not exists category text,
  add column if not exists date date,
  add column if not exists floor text,
  add column if not exists beds text,
  add column if not exists property_type text,
  add column if not exists builtup_area_sqft numeric,
  add column if not exists occupancy_status text,
  add column if not exists location_name text,
  add column if not exists full_location text,
  add column if not exists latitude numeric,
  add column if not exists longitude numeric,
  add column if not exists created_at timestamptz default timezone('utc', now());

create index if not exists idx_transactions_building_key
  on public.transactions (building_key);

create index if not exists transactions_building_key_date_idx
  on public.transactions (building_key, date desc);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'transactions_building_key_fkey'
      and conrelid = 'public.transactions'::regclass
  ) then
    alter table public.transactions
      add constraint transactions_building_key_fkey
      foreign key (building_key)
      references public.buildings(key)
      on delete cascade
      not valid;
  end if;
end $$;

alter table public.buildings enable row level security;
alter table public.transactions enable row level security;

drop policy if exists "Allow public read on buildings" on public.buildings;
create policy "Allow public read on buildings"
on public.buildings
for select
to anon, authenticated
using (true);

drop policy if exists "Allow service write on buildings" on public.buildings;
drop policy if exists "Allow service role write on buildings" on public.buildings;
create policy "Allow service role write on buildings"
on public.buildings
for all
to service_role
using (true)
with check (true);

drop policy if exists "Allow public read on transactions" on public.transactions;
create policy "Allow public read on transactions"
on public.transactions
for select
to anon, authenticated
using (true);

drop policy if exists "Allow service write on transactions" on public.transactions;
drop policy if exists "Allow service role write on transactions" on public.transactions;
create policy "Allow service role write on transactions"
on public.transactions
for all
to service_role
using (true)
with check (true);
