-- Ejari rent contracts per mapped building, imported from the DLD open-data
-- rents export. Mirrors the transactions market-cache table so the monthly
-- building report can summarize sales and rentals side by side.
create table if not exists public.rent_contracts (
  id bigint generated by default as identity primary key,
  building_key text not null,
  annual_amount numeric,
  contract_amount numeric,
  registration_date date,
  start_date date,
  end_date date,
  version text,
  rooms text,
  actual_area_sqm numeric,
  prop_type text,
  prop_sub_type text,
  usage text,
  location_name text,
  contract_number text,
  created_at timestamptz default timezone('utc', now())
);

create index if not exists idx_rent_contracts_building_key
  on public.rent_contracts (building_key);

create index if not exists rent_contracts_building_key_registration_date_idx
  on public.rent_contracts (building_key, registration_date desc);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'rent_contracts_building_key_fkey'
      and conrelid = 'public.rent_contracts'::regclass
  ) then
    alter table public.rent_contracts
      add constraint rent_contracts_building_key_fkey
      foreign key (building_key)
      references public.buildings(key)
      on delete cascade
      not valid;
  end if;
end $$;

alter table public.rent_contracts enable row level security;

drop policy if exists "Allow public read on rent_contracts" on public.rent_contracts;
create policy "Allow public read on rent_contracts"
on public.rent_contracts
for select
to anon, authenticated
using (true);

drop policy if exists "Allow service role write on rent_contracts" on public.rent_contracts;
create policy "Allow service role write on rent_contracts"
on public.rent_contracts
for all
to service_role
using (true)
with check (true);
